In [1]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-1f3025f0ddab44e290bf86bed48790c9f4fd1325a59b42e49701607ebb5b9546"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

text = "my name is sudhanshu and I am software engineer"

embedding = generate_embeddings(text)

In [10]:
print(type(embedding))
print(len(embedding))
print(embedding.shape)
print(embedding)

<class 'numpy.ndarray'>
1536
(1536,)
[-0.02166555 -0.02402906 -0.01707755 ... -0.02472421  0.02521082
 -0.02324122]


In [3]:
embedding.shape, embedding[:5]  # Display shape and first 5 elements of the embedding

((1536,),
 array([-0.02166555, -0.02402906, -0.01707755, -0.01105291, -0.02611452]))

In [4]:
len(embedding), embedding[:5]  # Display length and first 5 elements of the embedding

(1536,
 array([-0.02166555, -0.02402906, -0.01707755, -0.01105291, -0.02611452]))

In [ ]:
pip install sentence-transformers

In [ ]:
pip install --upgrade jupyter ipywidgets

In [ ]:
pip install hf_xet

In [5]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")

documents = [
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]
document_embeddings = model.encode(documents)

print(document_embeddings)


[[-0.04718245 -0.02091702  0.00366519 ...  0.05624256  0.07076066
  -0.0171463 ]
 [-0.05312933 -0.01502102 -0.00126578 ...  0.0036741  -0.0205426
   0.01957481]]


In [6]:
# Requires transformers>=4.51.0
# Requires sentence-transformers>=2.7.0

from sentence_transformers import SentenceTransformer

# Load the model
model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")

# We recommend enabling flash_attention_2 for better acceleration and memory saving,
# together with setting `padding_side` to "left":
# model = SentenceTransformer(
#     "Qwen/Qwen3-Embedding-0.6B",
#     model_kwargs={"attn_implementation": "flash_attention_2", "device_map": "auto"},
#     tokenizer_kwargs={"padding_side": "left"},
# )

# The queries and documents to embed
queries = [
    "What is the capital of China?",
    "Explain gravity",
]
documents = [
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]

# Encode the queries and documents. Note that queries benefit from using a prompt
# Here we use the prompt called "query" stored under `model.prompts`, but you can
# also pass your own prompt via the `prompt` argument
query_embeddings = model.encode(queries, prompt_name="query")
document_embeddings = model.encode(documents)

print(document_embeddings)
print(document_embeddings)

# Compute the (cosine) similarity between the query and document embeddings
similarity = model.similarity(query_embeddings, document_embeddings)
print(similarity)
# tensor([[0.7646, 0.1414],
#         [0.1355, 0.6000]])


[[-0.04718245 -0.02091702  0.00366519 ...  0.05624256  0.07076066
  -0.0171463 ]
 [-0.05312933 -0.01502102 -0.00126578 ...  0.0036741  -0.0205426
   0.01957481]]
[[-0.04718245 -0.02091702  0.00366519 ...  0.05624256  0.07076066
  -0.0171463 ]
 [-0.05312933 -0.01502102 -0.00126578 ...  0.0036741  -0.0205426
   0.01957481]]
tensor([[0.7646, 0.1414],
        [0.1355, 0.6000]])
