In [27]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-cf9524cd168f919e0d809fc31399177ff083add13efac86b9e7faf30229f78f3"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

text = "my name is sudhanshu and I am a software engineer"

embedding = generate_embeddings(text)

In [2]:
embedding

array([-0.02160565, -0.02425497, -0.02017822, ..., -0.0226905 ,
        0.02475743, -0.0228047 ], shape=(1536,))

In [3]:
len(embedding)

1536

In [3]:

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")

documents = [
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]
document_embeddings = model.encode(documents)


c:\Users\scl\anaconda3\envs\assignment_grader\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
c:\Users\scl\anaconda3\envs\assignment_grader\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\scl\.cache\huggingface\hub\models--Qwen--Qwen3-Embedding-0.6B. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING

In [6]:
len(document_embeddings[0])

1024

In [2]:
pip install sentence-transformers

  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
   ---------------------------------------- 0.0/241.4 MB ? eta -:--:--
   -- ------------------------------------- 16.3/241.4 MB 78.8 MB/s eta 0:00:03
   ------ --------------------------------- 41.7/241.4 MB 98.1 MB/s eta 0:00:03
   ---------- ---------------------------- 67.1/241.4 MB 104.3 MB/s eta 0:00:02
   -------------- ------------------------ 89.1/241.4 MB 107.3 MB/s eta 0:00:02
   --------------- ------------------------ 92.3/241.4 MB 87.9 MB/s eta 0:00:02
   ---------------- ---------------------- 103.5/241.4 MB 81.6 MB/s eta 0:00:02
   -------------------- ------------------ 129.0/241.4 MB 86.7 MB/s eta 0:00:02
   ------------------------ -------------- 154.4/241.4 MB 91.3 MB/s eta 0:00:01
   -------------------------- ------------ 163.6/241.4 MB 85.7 MB/s eta 0:00:01
   ---------------------------- ---------- 178.3/241.4 MB 87.6 MB/s eta 0:00:01
   ------------------------------- ------- 197.7/241.4 MB 84.2 M

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
easyocr 1.7.2 requires opencv-python-headless, which is not installed.
easyocr 1.7.2 requires pyclipper, which is not installed.
easyocr 1.7.2 requires python-bidi, which is not installed.
easyocr 1.7.2 requires Shapely, which is not installed.
easyocr 1.7.2 requires torchvision>=0.5, which is not installed.
scikit-image 0.25.2 requires tifffile>=2022.8.12, which is not installed.


In [ ]:

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")

documents = ["my name is sudhanshu and I am a software engineer",
             "sudhansh is my name and I am a software engineer",
             "apple is red and it is a fruit",
             "banana is yellow and it is a fruit",
             "sudhanshu is giving a class for gen ai and going to stat class for gen ai interview preparation",
]
document_embeddings = model.encode(documents)

In [8]:
document_embeddings

array([[ 0.03975108, -0.09927271, -0.00946082, ..., -0.02092933,
        -0.02810016, -0.00680683],
       [ 0.04646602, -0.10440628, -0.0122872 , ..., -0.0331007 ,
        -0.0295665 , -0.01203507],
       [-0.08274747,  0.05246587, -0.00250335, ..., -0.00065251,
         0.01755743,  0.01571287],
       [-0.05386702,  0.01229253, -0.00333654, ..., -0.00775528,
        -0.03061863,  0.0212334 ],
       [ 0.02187056, -0.06391601, -0.01035484, ...,  0.0135807 ,
        -0.00726835, -0.0066182 ]], dtype=float32)

In [9]:
from numpy import dot
from numpy.linalg import norm

In [15]:
sent1 = document_embeddings[0]
sent2 = document_embeddings[1]
sent3 = document_embeddings[2]
sent4 = document_embeddings[3]

In [11]:
dot(sent1, sent2) / (norm(sent1) * norm(sent2))

0.9600854

In [14]:
dot(sent1, sent3) / (norm(sent1) * norm(sent3))

0.38032132

In [16]:
dot(sent3, sent4) / (norm(sent3) * norm(sent4))

0.7854324

In [18]:
q = ["who is sudhanshu"]

In [19]:

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")


query_embed = model.encode(q)

In [20]:
query_embed

array([[ 0.02303059, -0.08273619, -0.01117361, ..., -0.0063008 ,
        -0.01095282, -0.01564785]], dtype=float32)

In [21]:
dist1= dot(query_embed, sent1) / (norm(query_embed) * norm(sent1))

In [22]:
dist2= dot(query_embed, sent2) / (norm(query_embed) * norm(sent2))

In [23]:
dist3 = dot(query_embed, sent3) / (norm(query_embed) * norm(sent3))

In [24]:
dsit4 = dot(query_embed, sent4) / (norm(query_embed) * norm(sent4))

In [25]:
dist1,dist2,dist3,dsit4

(array([0.6578402], dtype=float32),
 array([0.7150836], dtype=float32),
 array([0.37342265], dtype=float32),
 array([0.38690373], dtype=float32))

In [ ]:
generate_embeddings(text)

documents = ["my name is sudhanshu and I am a software engineer",
             "sudhansh is my name and I am a software engineer",
             "apple is red and it is a fruit",
             "banana is yellow and it is a fruit",
             "sudhanshu is giving a class for gen ai and going to stat class for gen ai interview preparation",
]

In [28]:
for i in documents:
    print(generate_embeddings(i))

[-0.02160565 -0.02425497 -0.02017822 ... -0.0226905   0.02475743
 -0.0228047 ]
[-0.02224723 -0.02059248  0.02232078 ... -0.01403475  0.02306848
 -0.01654753]
[-0.01825752  0.00227064 -0.01607493 ... -0.01501251 -0.0040043
  0.01943542]
[-0.02585626 -0.0151141   0.0063095  ...  0.00756257 -0.00574645
  0.01219947]
[-0.01920459  0.01377857  0.10068277 ...  0.00871052  0.01737079
 -0.01288679]
